### ISSUE TITLE
Upstream expansion not working

### ISSUE THREAD

**Issue by jimmccusker** [dlmcguinness/redrugs#23]
It seems to only do one step, and then stop. Downstream works fine. Also, sometimes it adds new (duplicate) edges to the graph.

See by starting with Melanoma, then do a 4-step upstream search for drugs.

**Comment by hesylvia** [comment]
Which version of Melanoma did you start with?

**Comment by jimmccusker** [comment]
Hmm. Not sure why the COSMIC diseases aren't showing up yet. Try "DRAVET SYNDROME".
